import config from "../config";
const SEARCH_ACTION_TYPES = config.actions.SEARCH_ACTION_TYPES;
const SEARCH_PARAMS_ACTION_TYPES = config.actions.SEARCH_PARAMS_ACTION_TYPES;
const ACTION_STATES = config.actions.ACTION_STATES;

export const PENDING_SEARCH_ACTION = `${SEARCH_ACTION_TYPES.SEARCH}_${ACTION_STATES.PENDING}`;
export const FULFILLED_SEARCH_ACTION = `${SEARCH_ACTION_TYPES.SEARCH}_${ACTION_STATES.FULFILLED}`;
export const REJECTED_SEARCH_ACTION = `${SEARCH_ACTION_TYPES.SEARCH}_${ACTION_STATES.REJECTED}`;
export const PENDING_SEARCH_MORE_ACTION = `${SEARCH_ACTION_TYPES.SEARCH_MORE}_${ACTION_STATES.PENDING}`;
export const FULFILLED_SEARCH_MORE_ACTION = `${SEARCH_ACTION_TYPES.SEARCH_MORE}_${ACTION_STATES.FULFILLED}`;
export const REJECTED_SEARCH_MORE_ACTION = `${SEARCH_ACTION_TYPES.SEARCH_MORE}_${ACTION_STATES.REJECTED}`;

export const SEARCH_ACTION = SEARCH_ACTION_TYPES.SEARCH;
export const SEARCH_MORE_ACTION = SEARCH_ACTION_TYPES.SEARCH_MORE;
export const SEARCH_RESET_ACTION = SEARCH_ACTION_TYPES.SEARCH_RESET;

export type SearchPromiseActionType =
  | typeof PENDING_SEARCH_ACTION
  | typeof FULFILLED_SEARCH_ACTION
  | typeof REJECTED_SEARCH_ACTION
  | typeof PENDING_SEARCH_MORE_ACTION
  | typeof FULFILLED_SEARCH_MORE_ACTION
  | typeof REJECTED_SEARCH_MORE_ACTION
  | typeof SEARCH_ACTION_TYPES.SEARCH_RESET;

export const UPDATE_SEARCH_OFFSET_ACTION =
  SEARCH_PARAMS_ACTION_TYPES.UPDATE_SEARCH_OFFSET;
export const UPDATE_SEARCH_QUERY_ACTION =
  SEARCH_PARAMS_ACTION_TYPES.UPDATE_SEARCH_QUERY;

export type SearchParamsActionType =
  | typeof SEARCH_RESET_ACTION
  | typeof UPDATE_SEARCH_OFFSET_ACTION
  | typeof UPDATE_SEARCH_QUERY_ACTION;

export type SearchActionType = typeof SEARCH_ACTION | typeof SEARCH_MORE_ACTION;
